postgres:
    image: postgres

taigaback:
    image: ipedrazas/taiga-back
    links:
        - postgres
    ports:
        - "8000:8000"

taigafront:
    image: ipedrazas/taiga-front
    links:
        - taigaback
    ports:
        - "80:80"
