postgres:
    image: postgres
    environment:
        - "POSTGRES_USER=taiga"
        - "POSTGRES_DB=taiga"

taigaback:
    image: dougg/taiga-back
    links:
        - postgres:postgres
    labels:
        traefik.port: "8000"
        traefik.backend: "taigaback"
    #   traefik.docker.network: "infrastructure"
        traefik.frontend.rule: "Host:localhost;PathPrefix:/api"

taigafront:
    image: dougg/taiga-front
    links:
        - taigaback:taiga-back
    environment:
        - "BASE_URL=http://localhost"
    labels:
        traefik.port: "80"
        traefik.backend: "taigafront"
        traefik.frontend.rule: "Host:localhost"

traefik:
    image: traefik
    command: -c /dev/null --web --docker --docker.domain=localhost --logLevel=DEBUG
    restart: always
    ports:
        - "80:80"
        - "8080:8080"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
